[package]
name = "rice"
version = "0.1.0"
authors = ["rayleigh <rayleigh@protonmail.com>"]

description = "Tool for configuring SteelSeries Rival 700 on Linux."
keywords = ["SteelSeries", "Rival 700", "SteelSeries Engine 3", "rival"]

license = "GPL-3.0"

[dependencies]
libusb = "0.3"